version: '3.8'
services:
#  Lest use Postgres as a service
# It will be hard to deploy it by docker container with backups and so on
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mood_app
    ports:
      - 6500:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
